/**
 * Dogs app
 * This is the API definition of the dogs owners app.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Coordinate from './Coordinate';

/**
 * The AreaFilter model module.
 * @module model/AreaFilter
 * @version 1.0
 */
class AreaFilter {
    /**
     * Constructs a new <code>AreaFilter</code>.
     * @alias module:model/AreaFilter
     * @param visibleArea {Array.<module:model/Coordinate>} 
     */
    constructor(visibleArea) { 
        
        AreaFilter.initialize(this, visibleArea);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, visibleArea) { 
        obj['visibleArea'] = visibleArea;
    }

    /**
     * Constructs a <code>AreaFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AreaFilter} obj Optional instance to populate.
     * @return {module:model/AreaFilter} The populated <code>AreaFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AreaFilter();

            if (data.hasOwnProperty('visibleArea')) {
                obj['visibleArea'] = ApiClient.convertToType(data['visibleArea'], [Coordinate]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Coordinate>} visibleArea
 */
AreaFilter.prototype['visibleArea'] = undefined;






export default AreaFilter;

