/**
 * Dogs app
 * This is the API definition of the dogs owners app.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChatMessage from './ChatMessage';
import User from './User';

/**
 * The Conversation model module.
 * @module model/Conversation
 * @version 1.0
 */
class Conversation {
    /**
     * Constructs a new <code>Conversation</code>.
     * @alias module:model/Conversation
     */
    constructor() { 
        
        Conversation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Conversation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Conversation} obj Optional instance to populate.
     * @return {module:model/Conversation} The populated <code>Conversation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Conversation();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('participant')) {
                obj['participant'] = User.constructFromObject(data['participant']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], [ChatMessage]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Conversation.prototype['id'] = undefined;

/**
 * @member {module:model/User} participant
 */
Conversation.prototype['participant'] = undefined;

/**
 * @member {Array.<module:model/ChatMessage>} message
 */
Conversation.prototype['message'] = undefined;






export default Conversation;

