/**
 * Dogs app
 * This is the API definition of the dogs owners app.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Coordinate model module.
 * @module model/Coordinate
 * @version 1.0
 */
class Coordinate {
    /**
     * Constructs a new <code>Coordinate</code>.
     * @alias module:model/Coordinate
     * @param longitude {Number} 
     * @param latitude {Number} 
     */
    constructor(longitude, latitude) { 
        
        Coordinate.initialize(this, longitude, latitude);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, longitude, latitude) { 
        obj['longitude'] = longitude;
        obj['latitude'] = latitude;
    }

    /**
     * Constructs a <code>Coordinate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Coordinate} obj Optional instance to populate.
     * @return {module:model/Coordinate} The populated <code>Coordinate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Coordinate();

            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} longitude
 */
Coordinate.prototype['longitude'] = undefined;

/**
 * @member {Number} latitude
 */
Coordinate.prototype['latitude'] = undefined;






export default Coordinate;

