/**
 * Dogs app
 * This is the API definition of the dogs owners app.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Gender from './Gender';

/**
 * The Dog model module.
 * @module model/Dog
 * @version 1.0
 */
class Dog {
    /**
     * Constructs a new <code>Dog</code>.
     * @alias module:model/Dog
     * @param name {String} 
     * @param breed {String} 
     * @param sex {module:model/Gender} 
     */
    constructor(name, breed, sex) { 
        
        Dog.initialize(this, name, breed, sex);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, breed, sex) { 
        obj['name'] = name;
        obj['breed'] = breed;
        obj['sex'] = sex;
    }

    /**
     * Constructs a <code>Dog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Dog} obj Optional instance to populate.
     * @return {module:model/Dog} The populated <code>Dog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Dog();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('breed')) {
                obj['breed'] = ApiClient.convertToType(data['breed'], 'String');
            }
            if (data.hasOwnProperty('sex')) {
                obj['sex'] = Gender.constructFromObject(data['sex']);
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], 'Date');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
            if (data.hasOwnProperty('profilePicture')) {
                obj['profilePicture'] = ApiClient.convertToType(data['profilePicture'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Dog.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Dog.prototype['name'] = undefined;

/**
 * @member {String} breed
 */
Dog.prototype['breed'] = undefined;

/**
 * @member {module:model/Gender} sex
 */
Dog.prototype['sex'] = undefined;

/**
 * @member {Date} dateOfBirth
 */
Dog.prototype['dateOfBirth'] = undefined;

/**
 * @member {Number} weight
 */
Dog.prototype['weight'] = undefined;

/**
 * @member {String} profilePicture
 */
Dog.prototype['profilePicture'] = undefined;

/**
 * @member {String} description
 */
Dog.prototype['description'] = undefined;

/**
 * @member {String} color
 */
Dog.prototype['color'] = undefined;






export default Dog;

