/**
 * Dogs app
 * This is the API definition of the dogs owners app.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Gender.
* @enum {}
* @readonly
*/
export default class Gender {
    
        /**
         * value: "MALE"
         * @const
         */
        "MALE" = "MALE";

    
        /**
         * value: "FEMALE"
         * @const
         */
        "FEMALE" = "FEMALE";

    
        /**
         * value: "OTHER"
         * @const
         */
        "OTHER" = "OTHER";

    

    /**
    * Returns a <code>Gender</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Gender} The enum <code>Gender</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

