/**
 * Dogs app
 * This is the API definition of the dogs owners app.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OnlineStatus.
* @enum {}
* @readonly
*/
export default class OnlineStatus {
    
        /**
         * value: "ONLINE"
         * @const
         */
        "ONLINE" = "ONLINE";

    
        /**
         * value: "OFFLINE"
         * @const
         */
        "OFFLINE" = "OFFLINE";

    

    /**
    * Returns a <code>OnlineStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OnlineStatus} The enum <code>OnlineStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

