/**
 * Dogs app
 * This is the API definition of the dogs owners app.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Coordinate from './Coordinate';
import Review from './Review';
import User from './User';

/**
 * The Park model module.
 * @module model/Park
 * @version 1.0
 */
class Park {
    /**
     * Constructs a new <code>Park</code>.
     * @alias module:model/Park
     * @param coordinate {module:model/Coordinate} 
     */
    constructor(coordinate) { 
        
        Park.initialize(this, coordinate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, coordinate) { 
        obj['coordinate'] = coordinate;
    }

    /**
     * Constructs a <code>Park</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Park} obj Optional instance to populate.
     * @return {module:model/Park} The populated <code>Park</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Park();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = User.constructFromObject(data['creator']);
            }
            if (data.hasOwnProperty('coordinate')) {
                obj['coordinate'] = Coordinate.constructFromObject(data['coordinate']);
            }
            if (data.hasOwnProperty('reviews')) {
                obj['reviews'] = ApiClient.convertToType(data['reviews'], [Review]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Park.prototype['id'] = undefined;

/**
 * @member {module:model/User} creator
 */
Park.prototype['creator'] = undefined;

/**
 * @member {module:model/Coordinate} coordinate
 */
Park.prototype['coordinate'] = undefined;

/**
 * @member {Array.<module:model/Review>} reviews
 */
Park.prototype['reviews'] = undefined;






export default Park;

