/**
 * Dogs app
 * This is the API definition of the dogs owners app.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Coordinate from './Coordinate';

/**
 * The RadiusFilter model module.
 * @module model/RadiusFilter
 * @version 1.0
 */
class RadiusFilter {
    /**
     * Constructs a new <code>RadiusFilter</code>.
     * @alias module:model/RadiusFilter
     * @param radius {Number} 
     * @param coordinate {module:model/Coordinate} 
     */
    constructor(radius, coordinate) { 
        
        RadiusFilter.initialize(this, radius, coordinate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, radius, coordinate) { 
        obj['radius'] = radius;
        obj['coordinate'] = coordinate;
    }

    /**
     * Constructs a <code>RadiusFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RadiusFilter} obj Optional instance to populate.
     * @return {module:model/RadiusFilter} The populated <code>RadiusFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RadiusFilter();

            if (data.hasOwnProperty('radius')) {
                obj['radius'] = ApiClient.convertToType(data['radius'], 'Number');
            }
            if (data.hasOwnProperty('coordinate')) {
                obj['coordinate'] = Coordinate.constructFromObject(data['coordinate']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} radius
 */
RadiusFilter.prototype['radius'] = undefined;

/**
 * @member {module:model/Coordinate} coordinate
 */
RadiusFilter.prototype['coordinate'] = undefined;






export default RadiusFilter;

