/**
 * Dogs app
 * This is the API definition of the dogs owners app.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The Review model module.
 * @module model/Review
 * @version 1.0
 */
class Review {
    /**
     * Constructs a new <code>Review</code>.
     * @alias module:model/Review
     * @param rating {Number} 
     */
    constructor(rating) { 
        
        Review.initialize(this, rating);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, rating) { 
        obj['rating'] = rating;
    }

    /**
     * Constructs a <code>Review</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Review} obj Optional instance to populate.
     * @return {module:model/Review} The populated <code>Review</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Review();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = User.constructFromObject(data['creator']);
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('timeStamp')) {
                obj['timeStamp'] = ApiClient.convertToType(data['timeStamp'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Review.prototype['id'] = undefined;

/**
 * @member {module:model/User} creator
 */
Review.prototype['creator'] = undefined;

/**
 * @member {Number} rating
 */
Review.prototype['rating'] = undefined;

/**
 * @member {String} text
 */
Review.prototype['text'] = undefined;

/**
 * @member {Date} timeStamp
 */
Review.prototype['timeStamp'] = undefined;






export default Review;

