/**
 * Dogs app
 * This is the API definition of the dogs owners app.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Tag model module.
 * @module model/Tag
 * @version 1.0
 */
class Tag {
    /**
     * Constructs a new <code>Tag</code>.
     * @alias module:model/Tag
     */
    constructor() { 
        
        Tag.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Tag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tag} obj Optional instance to populate.
     * @return {module:model/Tag} The populated <code>Tag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tag();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('tagType')) {
                obj['tagType'] = ApiClient.convertToType(data['tagType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Tag.prototype['name'] = undefined;

/**
 * @member {module:model/Tag.TagTypeEnum} tagType
 */
Tag.prototype['tagType'] = undefined;





/**
 * Allowed values for the <code>tagType</code> property.
 * @enum {String}
 * @readonly
 */
Tag['TagTypeEnum'] = {

    /**
     * value: "OFFERING"
     * @const
     */
    "OFFERING": "OFFERING",

    /**
     * value: "LOOKINGFOR"
     * @const
     */
    "LOOKINGFOR": "LOOKINGFOR"
};



export default Tag;

