/**
 * Dogs app
 * This is the API definition of the dogs owners app.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Conversation from './Conversation';
import Coordinate from './Coordinate';
import Dog from './Dog';
import Gender from './Gender';
import OnlineStatus from './OnlineStatus';
import Tag from './Tag';

/**
 * The User model module.
 * @module model/User
 * @version 1.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     */
    constructor() { 
        
        User.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('providerUid')) {
                obj['providerUid'] = ApiClient.convertToType(data['providerUid'], 'String');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = Gender.constructFromObject(data['gender']);
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], 'Date');
            }
            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = OnlineStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('profilePicture')) {
                obj['profilePicture'] = ApiClient.convertToType(data['profilePicture'], 'String');
            }
            if (data.hasOwnProperty('latestLocation')) {
                obj['latestLocation'] = Coordinate.constructFromObject(data['latestLocation']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [Tag]);
            }
            if (data.hasOwnProperty('conversations')) {
                obj['conversations'] = ApiClient.convertToType(data['conversations'], [Conversation]);
            }
            if (data.hasOwnProperty('dogs')) {
                obj['dogs'] = ApiClient.convertToType(data['dogs'], [Dog]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
User.prototype['id'] = undefined;

/**
 * @member {String} email
 */
User.prototype['email'] = undefined;

/**
 * @member {String} name
 */
User.prototype['name'] = undefined;

/**
 * @member {String} provider
 */
User.prototype['provider'] = undefined;

/**
 * @member {String} providerUid
 */
User.prototype['providerUid'] = undefined;

/**
 * @member {module:model/Gender} gender
 */
User.prototype['gender'] = undefined;

/**
 * @member {Date} dateOfBirth
 */
User.prototype['dateOfBirth'] = undefined;

/**
 * @member {String} bio
 */
User.prototype['bio'] = undefined;

/**
 * @member {module:model/OnlineStatus} status
 */
User.prototype['status'] = undefined;

/**
 * @member {String} profilePicture
 */
User.prototype['profilePicture'] = undefined;

/**
 * @member {module:model/Coordinate} latestLocation
 */
User.prototype['latestLocation'] = undefined;

/**
 * @member {Array.<module:model/Tag>} tags
 */
User.prototype['tags'] = undefined;

/**
 * @member {Array.<module:model/Conversation>} conversations
 */
User.prototype['conversations'] = undefined;

/**
 * @member {Array.<module:model/Dog>} dogs
 */
User.prototype['dogs'] = undefined;






export default User;

